//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public Nullable<int> ClassStudentId { get; set; }
        public Nullable<System.DateTime> MorningIn { get; set; }
        public Nullable<System.DateTime> MorningOut { get; set; }
        public Nullable<System.DateTime> AfternoonIn { get; set; }
        public Nullable<System.DateTime> AfternoonOut { get; set; }
    
        public virtual ClassStudent ClassStudent { get; set; }
    }
}
