//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseWork
    {
        public int Id { get; set; }
        public Nullable<int> ClassStudentId { get; set; }
        public Nullable<int> Course_ModuleId { get; set; }
        public Nullable<int> TestTypeId { get; set; }
        public Nullable<int> ModuleStandardId { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual ClassStudent ClassStudent { get; set; }
        public virtual Course_Module Course_Module { get; set; }
        public virtual TestType TestType { get; set; }
        public virtual ModuleStandard ModuleStandard { get; set; }
    }
}
