//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseWork
    {
        public int Id { get; set; }
        public Nullable<int> ClassStudentId { get; set; }
        public Nullable<int> TestType { get; set; }
        public Nullable<int> WrittenTest { get; set; }
        public Nullable<int> OralTest { get; set; }
        public Nullable<int> Presentation { get; set; }
        public Nullable<int> Assignment { get; set; }
        public Nullable<int> Project { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<bool> Lab { get; set; }
    
        public virtual ClassStudent ClassStudent { get; set; }
        public virtual TestType TestType1 { get; set; }
    }
}
