//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family()
        {
            this.Siblings = new HashSet<Sibling>();
        }
    
        public int FamilyId { get; set; }
        public int StudentId { get; set; }
        public bool SingleParent { get; set; }
        public string MomName { get; set; }
        public string MomEdu { get; set; }
        public Nullable<bool> MomWorkStatus { get; set; }
        public string MomJob { get; set; }
        public string MomFeildWork { get; set; }
        public string MomSectorJob { get; set; }
        public Nullable<decimal> MomSalary { get; set; }
        public string FatherName { get; set; }
        public string FatherEdu { get; set; }
        public Nullable<bool> FatherWorkStatus { get; set; }
        public string FatherJob { get; set; }
        public string FatherFeildWork { get; set; }
        public string FatherSectorJob { get; set; }
        public Nullable<decimal> FatherSalary { get; set; }
        public Nullable<int> NoSibling { get; set; }
        public Nullable<int> BirthOrd { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sibling> Siblings { get; set; }
    }
}
