//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleStandard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleStandard()
        {
            this.Course_Module = new HashSet<Course_Module>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> WrittenTest { get; set; }
        public Nullable<int> OralTest { get; set; }
        public Nullable<int> Assignment { get; set; }
        public Nullable<int> Presentation { get; set; }
        public Nullable<int> Project { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Module> Course_Module { get; set; }
    }
}
