//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleStandard
    {
        public int Id { get; set; }
        public Nullable<int> ClassStudentId { get; set; }
        public Nullable<int> MarkTypeId { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual ClassStudent ClassStudent { get; set; }
        public virtual MarkType MarkType { get; set; }
    }
}
