//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package_Course()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string CourseId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> FirstPay { get; set; }
        public Nullable<int> MonthlyInterest { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
