//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string CourseCode { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> CourseWorkId { get; set; }
    }
}
