//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ClassStudents = new HashSet<ClassStudent>();
            this.Families = new HashSet<Family>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> IntakeId { get; set; }
        public Nullable<int> SPMResultId { get; set; }
        public bool insurence { get; set; }
        public string Name { get; set; }
        public int age { get; set; }
        public System.DateTime DOB { get; set; }
        public int IC { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string PhoneNum { get; set; }
        public string OtherPhoneNum { get; set; }
        public string EmailAddress { get; set; }
        public string Religion { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassStudent> ClassStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families { get; set; }
        public virtual Intake Intake { get; set; }
        public virtual Package_Course Package_Course { get; set; }
        public virtual SPMResult SPMResult { get; set; }
    }
}
