//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.SPMResults = new HashSet<SPMResult>();
        }
    
        public int Id { get; set; }
        public string BM { get; set; }
        public string BI { get; set; }
        public string Math { get; set; }
        public string Sejarah { get; set; }
        public string BC { get; set; }
        public string Acc { get; set; }
        public string Chemistry { get; set; }
        public string Physic { get; set; }
        public string Bio { get; set; }
        public string Art { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPMResult> SPMResults { get; set; }
    }
}
